import { useEffect, useRef, useState } from "react";
import Head from "next/head";
import Image from "next/image";
// style
import styles from "../styles/Home.module.scss";
// constants
import { dropdownGroup } from "../utils/constants/dropdownGroup";
import { dropdownPortList } from "../utils/constants/dropdownPortList";
// components
import CardList from "../components/cardList";
import Itinerary from "../components/itinerary";
import DropdownSelect from "../components/dropdown";
import GroupShow from "../components/groupShow";
import Hero from "../components/hero";
import Banner from "../components/banner";
// logo and images
import logoIcon from "../../public/assets/images/logo.svg";
// types and interfaces
import { IDropdownList } from "../interfaces/IDropdownList";
import { IDataProps } from "../interfaces/IComponentsProps";
import { CardData } from "../utils/types/typeCard";
import { Port } from "../utils/types/typeCard";
// URL API
export const API_BASE_URL = "https://api.npoint.io/fb404a223a346cab07ec";
// mock
import {dataMock} from "../mock/data";

export default function Home({ data }: IDataProps) {
  const [inputDropdownValue, setInputDropdownValue] = useState<{label: string}>({ label: "Mostra tutti" });
  const [dataFiltered, setDataFiltered] = useState<CardData[]>([]);
  // array con la lista di tutte le dropdown select e per gestirne l'apertura e la chiusura
  const [dropdownList, setDropdownList] = useState<IDropdownList[]>([
    { id: 0, label: "groupList", isOpen: false, selectedOption: "" },
    { id: 1, label: "portList", isOpen: false, selectedOption: "" },
  ]);
  const portList = useRef<Port[]>([]);
  const isButtonVisible = useRef<boolean>(true);

  // crea un array con tutti i porti di partenza
  useEffect(() => {
    data.map((tour: CardData) => {
      if (!portList.current.some((item) => item.Port === tour.departure.Port))
        portList.current.push(tour.departure);
    });
  }, []);

  useEffect(() => {
    if (inputDropdownValue.label === "Mostra tutti") {
      setDataFiltered(data);
      isButtonVisible.current = true;
    } else if (
      inputDropdownValue.label !== "Mostra per porto di partenza" &&
      inputDropdownValue.label !== "Seleziona un porto"
    ) {
      setDataFiltered(
        data.filter((item) => item.departure.Port.includes(inputDropdownValue.label))
      );
      isButtonVisible.current = false;
    }
  }, [inputDropdownValue.label]);

  return (
    <>
      <Head>
        <title>Sea Adventures</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Mirko Montaina" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.header__logo}>
          <Image src={logoIcon} width={40} height={40} alt="logo" />
        </div>
      </header>
      <main className={styles.main}>
        <Hero title={"Sea adventures"} subtitle={"Boat Tours & Water Sports in Italy"} />
        <section className={styles.content}>
          <div className={styles.container}>
            <DropdownSelect
              options={dropdownGroup}
              handleChange={setInputDropdownValue}
              dropdown={dropdownList[0]}
              dropdownList={dropdownList}
              setDropdownList={setDropdownList}
            />
            <DropdownSelect
              options={dropdownPortList}
              handleChange={setInputDropdownValue}
              dropdown={dropdownList[1]}
              dropdownList={dropdownList}
              setDropdownList={setDropdownList}
            />
          </div>
          {inputDropdownValue.label === "Mostra per porto di partenza" ? (
            <GroupShow data={data} portList={portList.current} />
          ) : (
            <CardList data={dataFiltered} isButtonVisible={isButtonVisible.current} />
          )}
        </section>
        <Banner />
        <section className={styles.itinerary}>
          <Itinerary data={data} />
        </section>
      </main>
    </>
  );
}

/* SERVER SIDE RENDERING */
export async function getServerSideProps() {
  try {
    const res = await fetch(API_BASE_URL);
    const data = await res.json();
    return {
      props: { data },
    };
  } catch (error) {
    console.log(error);
    const data = dataMock;
    return {
      props: {data},
    }
  }
}
